version: "2.17"

services: 
  websocket:
    build:
      context: .
      dockerfile: /WebSocketGrpc/Dockerfile
      
  webapi:
    build:
      context: .
      dockerfile: /WebAPI/Dockerfile
      